---
- name: Install VNC server
  apt:  name=tightvncserver state=present
  sudo: yes
  tags:
    - sudoed

- name: Copy init script
  copy: src=vncserver-init dest=/etc/init.d/vncserver force=yes mode=755
  sudo: yes
  tags:
    - sudoed

- name:     Enable init script
  service:  name=vncserver state=started enabled=yes
  sudo:     yes
  tags:
    - sudoed

- name: Propagate VNC server via Bonjour
  copy: src=vncserver-avahi.xml dest=/etc/avahi/services/vncserver.service
  sudo: yes
  tags:
    - sudoed
  notify:
    - Reload avahi
