---
- name: Install git
  apt: name=git state=present
  sudo: yes
  tags:
    - sudoed

- name: Ensure there is place for git stuff
  file: dest=~/.git state=directory

- name: Copy git global ignore file
  copy: src=gitignore_global dest=~/.gitignore_global force=yes
  notify:
    - Configure the global ignore file
