---
- hosts:  raspberries
  user:   pi
  roles:
    - { role: git-client,    tags: ['git']  }
    - { role: zsh-terminal,  tags: ['zsh']  }
    - { role: vim-machine,   tags: ['vim']  }
    - { role: ruby-dev,      tags: ['ruby'] }
    - { role: vnc-server,    tags: ['vnc']  }
    - { role: wifi-client,   tags: ['wifi'] }
  vars:
    packages:
      - openssl
      - imagemagick
      - sqlite
      - htop
      - curl
      - wget
      - tmux
      - libnss-mdns # Bonjour
      - netatalk # Apple Filesharing Protocol
    projects:
    ruby:
      version: ruby-2.2.2
    machine_name: raspimir
