---
- name: Install ViM
  apt:  name=vim state=present
  sudo: yes
  tags:
    - sudoed

- name: Download Vundle
  git:  repo=https://github.com/gmarik/vundle.git
        dest=~/.vim/bundle/vundle

- name: Copy configs
  copy: src=config
        dest=~/.vim

- name: Copy vimrc
  copy: src=vimrc
        dest=~/.vimrc
        force=yes

- name: Create file for local only configs
  lineinfile: dest="~/.vim/localconfig.vim"
              state=present
              create=yes
              line="\" Intented for local only configurations"

- name: Vundle it
  command: vim +BundleInstall +qall
